[profile.testnet]
network = "testnet"
rpc_url = "https://soroban-testnet.stellar.org"
network_passphrase = "Test SDF Network ; September 2015"

[profile.mainnet]
network = "mainnet"
rpc_url = "https://mainnet.sorobanrpc.com"
network_passphrase = "Public Global Stellar Network ; September 2015"

[profile.sandbox]
network = "sandbox"
rpc_url = "http://localhost:8000"
network_passphrase = "Standalone Network ; February 2017"
